### ISSUE TITLE
make no work (wtf?)

### ISSUE THREAD

**Issue by c291bGxlc3Nzb29vZXM** [headshot2017/Classic64#1]
![image](https://user-images.githubusercontent.com/70554251/185258608-e124e1d9-c093-454f-8909-8f6630e9236c.png)

i don't know if make is fucked or i'm just a dumbass

**Comment by c291bGxlc3Nzb29vZXM** [comment]
tried putting a rom in the classic64 directory, still failed, reopening (sadglkfemrthgjurkt,h)

**Comment by headshot2017** [comment]
i recommend using the MSYS2 mingw64 environment for compiling the plugin: https://github.com/msys2/msys2-installer/releases/download/2022-06-03/msys2-x86_64-20220603.exe

**Comment by c291bGxlc3Nzb29vZXM** [comment]
Thank you!
