### ISSUE TITLE
Freebuild crash

### ISSUE THREAD

**Issue by c291bGxlc3Nzb29vZXM** [headshot2017/Classic64#10]
log:
```
----------------------------------------
Crash time: 05/09/2022 13:55:30
ClassiCube crashed.
Reason: Unhandled exception 0xC0000005 at 0x00007FFA9431F84D [0x0000000000000000,0x0000000000000000,]
Commit SHA: 59b7050 (OpenGL)
-- registers --
rax=0000000000000000 rbx=000000000AACE910 rcx=000000000AACEBC0
rdx=0000000000000000 rsi=0000000000000004 rdi=000000000090FE50
rip=00007FFA9431F84D rbp=000000000090F430 rsp=000000000090F400
r8 =000000000090F4E0 r9 =0000000000000000 r10=E5656DFF6D6DFEFF
r11=000000000AACC880 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
-- backtrace --
0x00007FFA9431F84D - Classic64(sm64_play_sound_global+200271)
0x00007FFA94320968 - Classic64(sm64_play_sound_global+204650)
0x00007FFA942EDAAF - Classic64(sm64_mario_tick+654)
0x00007FFA942E7D7A - Classic64
0x0000000000420DE2 - ClassiCube(Game_ChangeBlock+2603)
0x00000000004498AE - ClassiCube(DynamicLib_DescribeError+1069)
0x0000000000449A45 - ClassiCube(DynamicLib_DescribeError+1476)
0x00007FFB0C3654E0 - KERNEL32(BaseThreadInitThunk+16)
0x00007FFB0DDE485B - ntdll(RtlUserThreadStart+43)
-- modules --
```

specs:
operating system: windows 11 home, 10.0.22000, 64 bit
laptop brand: MSI
model: gf63 thin 10sc
processor: intel core i5-10500h cpu @ 2.50 ghz 2496 mhz 6 cores
installed physical memory: 8.00 gb

**Comment by c291bGxlc3Nzb29vZXM** [comment]
Works in latest, closing

**Comment by c291bGxlc3Nzb29vZXM** [comment]
Nevermind.
![image](https://user-images.githubusercontent.com/70554251/188513413-5ede0bf1-7dbd-4cfb-a0e3-39f8daa5979a.png)

**Comment by headshot2017** [comment]
i have triggered some crashes:

![crash](https://cdn.discordapp.com/attachments/710557654992551936/1017842140983869450/unknown.png)
i don't know what happened in this one, but it was when i just entered a map while as mario
<br/>
![crash2](https://media.discordapp.net/attachments/710557654992551936/1017844658153455686/unknown.png)
i entered this map and i was stuck inside a block, so mario couldn't spawn. i switched to the default model, unstucked myself, switched to mario then this one occurred. this one is easily fixable by increasing the maximum vertex limit for the surface debugger
<br/>
![crash3](https://cdn.discordapp.com/attachments/710557654992551936/1017860875828334692/unknown.png)
same crash as the first one

i'm convinced the 1st and 3rd images are the main problem in this issue. i will look into this and fix it

**Comment by headshot2017** [comment]
it should be fixed by now. if it doesn't crash again you may close the issue

**Comment by headshot2017** [comment]
on second thought, this crash is kind of difficult to trigger since it happens randomly, so i will be closing this issue as completed. if it happens again please create a new one
