### ISSUE TITLE
color codes

### ISSUE THREAD

**Issue by RealGranfill** [headshot2017/Classic64#14]
I tried the "/client mario64 settings" and i wanted to change color codes but it said something about rgb values can you help me?

**Comment by headshot2017** [comment]
it isn't that hard.
for example, if you wish to set Mario's shirt and hat color to green, you do:
`/client mario64 settings color_shirthat 0 255 0`

the last three numbers, `0 255 0`, are rgb values, in a range from 0 to 255.
`0: red, 255: green, 0: blue`

you could also play around with colors on MSPaint or something if you wish

**Comment by RealGranfill** [comment]
Thanks now i know RGB
