### ISSUE TITLE
Make it so that whenever the Mario model turns the players camera angle follows as well [Enhancement]

### ISSUE THREAD

**Issue by UmbreoClaw** [headshot2017/Classic64#16]
The Mario model POV and the Player POV arent synced and that can result in the Mario model sometimes facing in different directions other than what the player is facing, so perhaps make it so that theres an option to make it so that the players POV is forced into the mario models POV?

**Comment by headshot2017** [comment]
i'll consider this as a plugin setting in `/client mario64 settings`

**Comment by UmbreoClaw** [comment]
Alright, that would be pretty cool imo, since it slightly bothered me how it's not lined up

**Comment by headshot2017** [comment]
i re-read this one more time and unless i misunderstood and you meant the other way around "make mario turn to where the camera is facing", this is already a feature with the "camera" setting: `/client mario64 settings camera on`
