### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by N00neIsHere** [headshot2017/Classic64#17]
When trying to run the plugin on Windows 10, I get the following error: Entry Point Not Found
The procedure entry point CPE_SendPluginMessage could not be located in the dynamic link library [filepath] Classic64.dll

have the correct rom named properly with the correct SHA-1 hash in the folder with it.

**Comment by headshot2017** [comment]
sounds like an old client version issue, try updating the client

**Comment by N00neIsHere** [comment]
Was just about to write a comment saying I updated the client and it started working. Apparantly the itch.io version of Classicube is outdated.
