### ISSUE TITLE
No Win 32 bit Version of the plugin.

### ISSUE THREAD

**Issue by AhmedBro171** [headshot2017/Classic64#23]
You should add a Win 32 bit version,  **That could help players**  Which have 32 Bit Windows.

**Comment by headshot2017** [comment]
i've planned to do this in the future

**Comment by headshot2017** [comment]
hi again, i'm working on porting Classic64 to 32 bit and other platforms like mac and linux for update v1.1, if you're still there, can you test this 32bit version?
[Classic64.zip](https://github.com/headshot2017/Classic64/files/13897404/Classic64.zip)
