### ISSUE TITLE
Building to Mobile

### ISSUE THREAD

**Issue by MarioGuyWasTakenAgain** [headshot2017/Classic64#24]
Is building this for mobile possible, If so, How?

**Comment by headshot2017** [comment]
i have yet to see a single classicube plugin with support for android/iOS
![Screenshot_20230910_000958_Discord](https://github.com/headshot2017/Classic64/assets/36455681/cf94e473-2895-4e81-b6a6-39ea01665f86)

**Comment by stonedDiscord** [comment]
No
